" no vi compatibility

source $HOME/.vim/config/general.vimrc
source $HOME/.vim/config/keys.vimrc

 " PLUGINS
source $HOME/.vim/config/plugins.vimrc

source $HOME/.vim/config/autocomplete.vimrc
source $HOME/.vim/config/appearance.vimrc
source $HOME/.vim/config/vimtex.vimrc
source $HOME/.vim/config/nerdtree.vimrc
source $HOME/.vim/config/indentline.vimrc
source $HOME/.vim/config/fzf.vimrc
source $HOME/.vim/config/codechecking.vimrc 

source $HOME/.vim/config/vimwiki.vimrc

" source $HOME/.vim/config/utltisnips.vimrc
" source $HOME/.vim/config/syntastic.vimrc
" source $HOME/.vim/config/ctrlp.vimrc
