" no vi compatibility
set nocompatible

" filetype func off
filetype off 

set autoindent
set expandtab
set softtabstop =4
set shiftwidth =4
set shiftround

set backspace =indent,eol,start
set hidden
set laststatus =2

" Set linenumbers
set number
set relativenumber

" Nerdtree hotkey to C-n
autocmd vimenter * NERDTree
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p
" Use ctags
command! MakeTags !ctags -R .

" finding files in vim
set path+=**
set wildmenu

" Options for vimtex
let g:latex_view_general_viewer = "zathura"
let g:vimtex_view_method = "zathura"

" initialize vundle
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" All the plugins are listed here
Plugin 'VundleVim/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'lervag/vimtex'
Plugin 'scrooloose/nerdtree'

" start all the plugins above
call vundle#end()

" filetype func on
filetype plugin indent on

" Solarized dark
syntax enable
set background=dark
colorscheme solarized

