detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu

mqtt:
  # Required: host name
  host: mosquitto
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  #user: mqtt_user
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  #password: password
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

cameras:
  front:
    ffmpeg:
      inputs:
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}:554/h264Preview_01_sub
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}/bcs/channel0_sub.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            # - clips
            # - rtmp
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}:554/h264Preview_01_main
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - clips
            - rtmp
    width: 640
    height: 480
    fps: 4
    
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      # required_zones: []
      # objects:
      #   - person
      pre_capture: 5
      post_capture: 5

    record:
      enabled: False
      retain_days: 10

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      required_zones: []

    objects:
      track:
        - person
      filters:
        person:
          mask: 538,155,640,262,640,413,523,281,471,226,429,171,347,82,370,37

    zones:
      porch:
        coordinates: 0,480,396,480,305,196,324,0,114,0
      front_steps:
        coordinates: 455,203,515,282,589,379,364,364,290,225,313,159
      street:
        coordinates: 538,155,640,262,640,413,523,281,471,226,429,171,347,82,370,37

  back:
    ffmpeg:
      inputs:
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}:554/h264Preview_01_sub
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}/bcs/channel0_sub.bcs?token=sdasdasd&channel=0&stream=1&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - detect
            # - clips
            # - rtmp
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}:554/h264Preview_01_main
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - clips
            - rtmp
    width: 640
    height: 480
    fps: 4

    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5

    record:
      enabled: False
      retain_days: 10

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 270
      required_zones: []

    objects:
      track:
        - person

      
# ffmpeg + global_args + input_args + -i + input + output_args
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args: # only use for RTMP
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rw_timeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
  # input_args:
  #   - -avoid_negative_ts
  #   - make_zero
  #   - -fflags
  #   - +genpts+discardcorrupt
  #   - -rtsp_transport
  #   - tcp
  #   - -stimeout
  #   - '5000000'
  #   - -use_wallclock_as_timestamps
  #   - '1'
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vcoded copy -acodec copy
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vcodec copy -acodec copy
    rtmp: -c copy -f flv

clips:
  max_seconds: 300 # max length of video clip
  retain: # retentation limit on clips
    default: 3 # keep for 10 days
    objects: # per object retention policy
      person: 10

record:
  retain_days: 3

snapshots: 
  retain:
    default: 10
    objects:
      person: 10
