detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  # Required: host name
  host: mosquitto
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  #user: mqtt_user
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  #password: password
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

cameras:
  front:
    ffmpeg:
      inputs:
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}:554/h264Preview_01_sub
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}/bcs/channel0_sub.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - rtmp
            # - detect
            # - clips
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}:554/h264Preview_01_main
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - clips
            - detect
            # - rtmp
    width: 2560
    height: 1920
    fps: 5
    
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      # required_zones: []
      # objects:
      #   - person
      pre_capture: 5
      post_capture: 5

    record:
      enabled: False
      retain_days: 10

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 480
      required_zones: []

    motion:
      mask:    
        - 2560,653,2560,873,2338,1187,1749,1920,1604,1920,1422,1527,1851,904,2142,353
        - 1436,164,1504,0,1647,53,1778,142,1684,327,1549,418,1582,538,1711,642,1769,773,1656,884,1538,789,1198,724,1269,551,1389,311
        - 1109,0,1051,107,953,67,971,0


    zones:
      porch:
        coordinates: 0,1920,0,1700,0,1313,0,796,0,0,589,0,1360,0,1118,760,1291,1227,1462,1580,1633,1920
      front_yard:
        coordinates: 2129,1429,2449,1920,1616,1920,1287,1216,1129,842,1436,89,1549,667
      street:
        coordinates: 2560,1509,2560,960,2560,658,2413,520,1922,211,1524,0,1369,304,1536,553,2136,1398,2471,1920,2560,1920

  back:
    ffmpeg:
      inputs:
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}:554/h264Preview_01_sub
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}/bcs/channel0_sub.bcs?token=sdasdasd&channel=0&stream=1&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - rtmp
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}:554/h264Preview_01_main
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - clips
            - detect
            # - rtmp
    width: 2560
    height: 1920
    fps: 5

    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5

    record:
      enabled: False
      retain_days: 10

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 480
      required_zones: []

    zones:
      back_yard:
        coordinates: 0,1920,2560,1920,2560,1013,1709,442,1302,453,767,449,0,1391
      alley:
        coordinates: 0,0,2560,0,2560,484,2436,478,1911,440,1511,456,1047,444,418,471,0,484
      
# ffmpeg + global_args + input_args + -i + input + output_args
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args: # only use for RTMP
    # - -fflags
    # - nobuffer
    # - -flags
    # - low_delay
    # - -strict
    # - experimental
    # - rw_timeout
    # - '5000000'
    # - -f
    # - live_flv

    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rw_timeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
    - -f
    - live_flv
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vcoded copy -acodec copy
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vcodec copy -acodec copy
    rtmp: -c copy -f flv

clips:
  max_seconds: 300 # max length of video clip
  retain: # retentation limit on clips
    default: 3 # keep for 10 days
    objects: # per object retention policy
      person: 5

record:
  retain_days: 3

snapshots: 
  retain:
    default: 10
    objects:
      person: 10

motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 25
  # Optional: Minimum size in pixels in the resized motion image that counts as motion
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will make motion detection more sensitive to smaller
  # moving objects.
  contour_area: 100
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging the motion delta across multiple frames (default: shown below)
  # Higher values mean the current frame impacts the delta a lot, and a single raindrop may register as motion.
  # Too low and a fast moving person wont be detected as motion.
  delta_alpha: 0.2
  # Optional: Alpha value passed to cv2.accumulateWeighted when averaging frames to determine the background (default: shown below)
  # Higher values mean the current frame impacts the average a lot, and a new object will be averaged into the background faster.
  # Low values will cause things like moving shadows to be detected as motion for longer.
  # https://www.geeksforgeeks.org/background-subtraction-in-an-image-using-concept-of-running-average/
  frame_alpha: 0.2
  # Optional: Height of the resized motion frame  (default: 1/6th of the original frame height)
  # This operates as an efficient blur alternative. Higher values will result in more granular motion detection at the expense of higher CPU usage.
  # Lower values result in less CPU, but small changes may not register as motion.
  frame_height: 180

objects:
  track:
    - person
    - cat
    - dog
  filters:
    person:
      # mask:
      #   - 395,68,471,117,427,211,396,207,380,202,351,181,317,145,343,89
      # Optional: minimum width*height of the bounding box for the detected object (default: 0)
      min_area: 20000
      # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
      max_area: 24000000
      # Optional: minimum score for the object to initiate tracking (default: shown below)
      min_score: 0.7
      # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
      threshold: 0.7
