detectors:
  coral:
    type: edgetpu
    device: usb

mqtt:
  # Required: host name
  host: mosquitto
  # Optional: port (default: shown below)
  port: 1883
  # Optional: topic prefix (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  topic_prefix: frigate
  # Optional: client id (default: shown below)
  # WARNING: must be unique if you are running multiple instances
  client_id: frigate
  # Optional: user
  #user: mqtt_user
  # Optional: password
  # NOTE: Environment variables that begin with 'FRIGATE_' may be referenced in {}.
  #       eg. password: '{FRIGATE_MQTT_PASSWORD}'
  #password: password
  # Optional: interval in seconds for publishing stats (default: shown below)
  stats_interval: 60

cameras:
  front:
    ffmpeg:
      inputs:
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}:554/h264Preview_01_sub
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}/bcs/channel0_sub.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - rtmp
            # - detect
            # - clips
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}:554/h264Preview_01_main
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_FRONT_CAM_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - clips
            - detect
            # - rtmp
    width: 2560
    height: 1920
    fps: 15
    
    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      # required_zones: []
      # objects:
      #   - person
      pre_capture: 5
      post_capture: 5

    record:
      enabled: False
      retain_days: 10

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 480
      required_zones: []

    motion:
      mask:    
        - 2560,671,2560,849,2373,1013,2211,1120,2089,1207,1956,1316,1769,1429,1542,1600,1416,1469,1349,1369,1320,1193,1749,831,2113,342

    objects:
      track:
        - person
        - cat
        - dog
      filters:
        person:
          # mask:
          #   - 395,68,471,117,427,211,396,207,380,202,351,181,317,145,343,89
          # Optional: minimum width*height of the bounding box for the detected object (default: 0)
          min_area: 20000
          # Optional: maximum width*height of the bounding box for the detected object (default: 24000000)
          max_area: 24000000
          # Optional: minimum score for the object to initiate tracking (default: shown below)
          min_score: 0.7
          # Optional: minimum decimal percentage for tracked object's computed score to be considered a true positive (default: shown below)
          threshold: 0.7

    zones:
      porch:
        coordinates: 0,1920,0,1700,0,1313,0,796,0,0,589,0,1360,0,1118,760,1291,1227,1462,1580,1633,1920
    #   front_steps:
    #     coordinates: 455,203,515,282,589,379,364,364,290,225,313,159
    #   street:
    #     coordinates: 538,155,640,262,640,413,523,281,471,226,429,171,347,82,370,37

  back:
    ffmpeg:
      inputs:
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}:554/h264Preview_01_sub
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}/bcs/channel0_sub.bcs?token=sdasdasd&channel=0&stream=1&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - rtmp
        # - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}:554/h264Preview_01_main
        - path: rtmp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_BACK_CAM_IP}/bcs/channel0_main.bcs?token=sdasdasd&channel=0&stream=0&user={FRIGATE_CAM_USERNAME}&password={FRIGATE_CAM_PASSWORD}
          roles:
            - clips
            - detect
            # - rtmp
    width: 2560
    height: 1920
    fps: 15

    detect:
      enabled: True
      max_disappeared: 25

    clips:
      enabled: True
      pre_capture: 5
      post_capture: 5

    record:
      enabled: False
      retain_days: 10

    snapshots:
      enabled: True
      timestamp: False
      bounding_box: True
      crop: False

    mqtt:
      enabled: True
      timestamp: True
      bounding_box: True
      crop: True
      height: 480
      required_zones: []

    objects:
      track:
        - person
        - cat
        - dog

      
# ffmpeg + global_args + input_args + -i + input + output_args
ffmpeg:
  global_args: -hide_banner -loglevel warning
  hwaccel_args:
    - -hwaccel
    - vaapi
    - -hwaccel_device
    - /dev/dri/renderD128
    - -hwaccel_output_format
    - yuv420p
  input_args: # only use for RTMP
    # - -fflags
    # - nobuffer
    # - -flags
    # - low_delay
    # - -strict
    # - experimental
    # - rw_timeout
    # - '5000000'
    # - -f
    # - live_flv

    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer
    - -flags
    - low_delay
    - -strict
    - experimental
    - -fflags
    - +genpts+discardcorrupt
    - -rw_timeout
    - '5000000'
    - -use_wallclock_as_timestamps
    - '1'
    - -f
    - live_flv
  output_args:
    detect: -f rawvideo -pix_fmt yuv420p
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vcoded copy -acodec copy
    clips: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -vcodec copy -acodec copy
    rtmp: -c copy -f flv

clips:
  max_seconds: 300 # max length of video clip
  retain: # retentation limit on clips
    default: 3 # keep for 10 days
    objects: # per object retention policy
      person: 5

record:
  retain_days: 3

snapshots: 
  retain:
    default: 10
    objects:
      person: 10
